### ISSUE TITLE
Doesn't allow for parameters like --foo='a b  c'

### ISSUE THREAD

**Issue by cullylarson** [xxorax/node-shell-escape#12]
For example:

``` js
console.log(shellescape([
  "--foo=",
  "a b c"
]))
// '--foo=' 'a b c'

console.log(shellescape([
  "--foo=a b c"
]))
// '--foo=a b c'
```

Neither of those options work.  What you need is something like: `--foo='a b c'`

**Comment by petemoore** [comment]
@cullylarson @dorianj @dypsilon @brillout The second option is correct. If you write `--foo='a b c'` in a shell, it will be interpreted as single token `--foo=a b c` e.g. for passing to a command as a command line argument. Therefore, in the shell, `--foo='a b c'` is exactly the same as `'--foo=a b c'`. Try replacing the former with the latter, anywhere you were previously using it, and you'll see you will get the same result. :-)

**Comment by xxorax** [comment]
It's right. 
This is the same for the shell:
`shellescape(["--foo=a b c"])` == `'--foo=a b c'` == `--foo='a b c'`

**Comment by binki** [comment]
Sorry for the  bugspam.

I just wanted to note that, on Windows, the different ways of quoting do yield different results because [Windows passes CommandLine as a string rather than an array](https://stackoverflow.com/a/4094897/429091).

You can see an example of how quoting works in Windows here: https://gist.github.com/binki/d8be8a7eb90340d660582e0ba8caf08a
